version: 2

sources:
  - name: sep_raw
    database: project-f311ccd4-12f3-441a-822
    schema: sep_raw
    tables:
      - name: effectifs
      - name: depenses
      - name: openmedic_2019
      - name: openmedic_2020
      - name: openmedic_2021
      - name: openmedic_2022
